name: animated_expand
description: "A customizable and animated expandable widget for Flutter. `AnimatedExpand` allows you to smoothly expand and collapse UI elements with animations. It supports both **vertical and horizontal** expansion, custom controllers, and fine-tuned animation settings."
version: 1.0.1
homepage: https://github.com/geo1796/animated_expand
repository: https://github.com/geo1796/animated_expand
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: